[package]
name = "test_go_rust_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "goodboy"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.170"
tokio = { version = "1", features = ["full"] }
